### PR TITLE
Develop bitcoinde adjustments

### PR DESCRIPTION
**Pull request by bryan4887**
@matthewdowney 
Should be trivial changes, but take a look anyway.

### CODE REVIEW

**Comment by matthewdowney** [comment]
Looks good to me.

**Comment by bryan4887** [comment]
Thanks.  BTW, how long do you think it would take you to implement the
websocket API in XChange for Coinbase Exchange?

https://docs.exchange.coinbase.com/#websocket-feed

Best,

Bryan

**Comment by matthewdowney** [comment]
Hmm, I'm honestly not sure.  I haven't worked with websockets before, but I
don't think it would take too long to figure out.

**Comment by bryan4887** [comment]
Ok. Just curious. Don't worry about it for now.

On Sunday, June 7, 2015, Matthew Downey <notifications@github.com> wrote:

> Hmm, I'm honestly not sure. I haven't worked with websockets before, but I
> don't think it would take too long to figure out.
> On Jun 6, 2015 7:53 PM, "Bryan Hernandez" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Thanks. BTW, how long do you think it would take you to implement the
> > websocket API in XChange for Coinbase Exchange?
> >
> > https://docs.exchange.coinbase.com/#websocket-feed
> >
> > Best,
> >
> > Bryan
> >
> >
> > On Sat, Jun 6, 2015 at 6:45 PM, Matthew Downey <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Looks good to me.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/SonarTrading/XChange/pull/2#issuecomment-109659857
> >.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SonarTrading/XChange/pull/2#issuecomment-109660252>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SonarTrading/XChange/pull/2#issuecomment-109748931>.
>


-- 
Sent from my phone

**Pull request merged**
